version: '3'

services:

  php:
    build:
      context: ./php
    volumes:
        - ./public:/var/www/public_html

  web:
    image: nginx:latest
    ports:
        - "8000:80"
    volumes:
        - ./public:/var/www/public_html
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
        - php

