version: '3'

services:

  # db:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_DATABASE: akaunting
  #     MYSQL_ROOT_PASSWORD: my-secret-password
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./data:/var/lib/mysql
  db:
    image: percona/percona-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
    command:
      --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password

  php:
    build:
      context: ./php
    volumes:
      - ./public:/var/www/public_html

  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/public_html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
      - php

